<h1>Numpy Fast Tutorial </h1>

In [1]:
##First of all we import the numpy library
#To install the library run pip install numpy
import numpy as np

In [8]:
#Let's create a simple array containing 1,2,3 using numpy and python list
x_numpy= np.array([1,2,3])
x_list= [1,2,3]

In [4]:
#Now we change the first element in x_list to "H"
x_list[0]= 'H'
x_list

['H', 2, 3]

In [9]:
#Now we change the first element in x_numpy to "H"
x_numpy

array([1, 2, 3])

<h2>What you can do with Numpy? </h2>
<p>A numpy array is like a C array as it has the following properties:</p>
<ul>
<li> It has a fixed length.
<li> It has a constant datatype
</ul>

In [12]:
#Let's create a list of integers from 1 to 100
arr=np.arange(0,100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [13]:
#Now let's say we want to get the integers from index 5 to 20 in the above list.
new_arr= np.zeros(20-5) #Create array of zeros of length 10
print(new_arr)
for i in range(5,20):
    new_arr[i-5]= arr[i]
print(new_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]


In [14]:
#Let's optimize the above statement
arr[5:20]


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
#To get the element from the first element to a certain integer (50)
arr[0:50]
arr[:50]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [19]:
#To get the elements from a certain integer to end of list
arr[50:len(arr)]
arr[50:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [20]:
#How to only certain indices
arr[[1,2,3,50]]

array([ 1,  2,  3, 50])

<h2>Why we use it?</h2>
<p>Numpy is used for performing complex mathematical operations on arrays and matrices</p>

In [21]:
x=np.arange(0,1000,100)
y=np.arange(0,100,10)
print(x)
print(y)

[  0 100 200 300 400 500 600 700 800 900]
[ 0 10 20 30 40 50 60 70 80 90]


In [22]:
#Let's add the number 10 to array X
x+10

array([ 10, 110, 210, 310, 410, 510, 610, 710, 810, 910])

In [23]:
#Subtract, multiply, divide
x-10,x*10,x/10

(array([-10,  90, 190, 290, 390, 490, 590, 690, 790, 890]),
 array([   0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000]),
 array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.]))

In [24]:
#Now let's add the 2 arrays
x+y,x*y


(array([  0, 110, 220, 330, 440, 550, 660, 770, 880, 990]),
 array([    0,  1000,  4000,  9000, 16000, 25000, 36000, 49000, 64000,
        81000]))

In [25]:
#Let's say we want the biggest element in an array
x= np.random.randint(0,1000,10)
print(x)
np.max(x)

[168 308 488 844 109 147 227 481 812 606]


844

<h3>You can do any operation on your array</h3>
<ul>
<li> Get max element and min element.
<li> Get sum of all elements in list.
<li> Get mean and standard deviation.
<li>Much Much more
</ul> 

In [26]:
#Now let's create a 3x3 matrix
matrix= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
#Let's see the shape of the matrix
matrix.shape


(3, 3)

In [30]:
#Let's get sum among the columns
#Let's get sum among the rows
print(np.sum(matrix))
print(np.sum(matrix,axis=0))
print(np.sum(matrix,axis=1))



45
[12 15 18]
[ 6 15 24]


In [33]:
#Try to reshape the array (3x3) -->(9x1)
print(matrix.reshape((9,1)))
print(matrix.flatten())



(9, 1)
(9,)


In [35]:
#Slice the matrix
print(matrix[1:,:2])


[[4 5]
 [7 8]]
