<h1>Numpy Fast Tutorial </h1>

In [ ]:
##First of all we import the numpy library
#To install the library run pip install numpy
import numpy as np

In [ ]:
#Let's create a simple array containing 1,2,3 using numpy and python list
x_numpy= np.array([1,2,3])
x_list= [1,2,3]

In [ ]:
#Now we change the first element in x_list to "H"
x_list[0]= 'H'

In [ ]:
#Now we change the first element in x_numpy to "H"
x_numpy[0]= 'H'

<h2>What you can do with Numpy? </h2>
<p>A numpy array is like a C array as it has the following properties:</p>
<ul>
<li> It has a fixed length.
<li> It has a constant datatype
</ul>

In [ ]:
#Let's create a list of integers from 1 to 100
arr=np.arange(0,100)
arr

In [ ]:
#Now let's say we want to get the integers from index 5 to 20 in the above list.
new_arr= np.zeros(20-5) #Create array of zeros of length 10
print(new_arr)
for i in range(5,20):
    new_arr[i-5]= arr[i]
print(new_arr)

In [ ]:
#Let's optimize the above statement
new_arr2= arr[5:20]
new_arr2

In [ ]:
#To get the element from the first element to a certain integer


In [ ]:
#To get the elements from a certain integer to end of list

In [ ]:
#How to only certain indices

<h2>Why we use it?</h2>
<p>Numpy is used for performing complex mathematical operations on arrays and matrices</p>

In [25]:
x=np.arange(0,1000,100)
y=np.arange(0,100,10)
print(x)
print(y)

[  0 100 200 300 400 500 600 700 800 900]
[ 0 10 20 30 40 50 60 70 80 90]


In [23]:
#Let's add the number 10 to array X

In [27]:
#Subtract, multiply, divide


In [32]:
#Now let's add the 2 arrays


In [35]:
#Let's say we want the biggest element in an array
x= np.random.randint(0,1000,10)
# print(x)
# np.max(x)

[ 14 472 646 237 508 186 665  31 458 942]


942

<h3>You can do any operation on your array</h3>
<ul>
<li> Get max element and min element.
<li> Get sum of all elements in list.
<li> Get mean and standard deviation.
<li>Much Much more
</ul> 

In [37]:
#Now let's create a 3x3 matrix
matrix= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
#Let's see the shape of the matrix


In [41]:
#Let's get sum among the columns
#Let's get sum among the rows



In [46]:
#Try to reshape the array (3x3) -->(9x1)


In [50]:
#Slice the matrix


array([[2, 3],
       [5, 6],
       [8, 9]])